### ISSUE TITLE
Packing of trips

### ISSUE THREAD

**Issue by t2gran** [entur/r5#14]
### Problem
RangeRaptor has a limited guarantee on packing trips towards the origin. It is only valid within the search time window.

The trips found in the first iteration of RangeRaptor does not guarantee that there is not another trip that leave later and arrive at the same time at the destination. Typically for a 40 minute time window this is the majority of the trips found. 

It does, however, guarantee that the intermediate transit legs are shifted towards the beginning of the trip.

### Solution
The simplest solution to this is of cause to extend the time window (see abyrd´s cpmment below), but this might cause other challenges like degraded performance.

**Comment by t2gran** [comment]
This might not be a big problem, because the traveller is most likely to to choose one of the trips arriving early - and these trips are normally optimal. This problem becomes less the more we increase the time window.

**Comment by abyrd** [comment]
I don't understand the reasoning here. If I find a trip at 14:30 arriving at 15:00, then step back 1 minute and find a trip leaving at 14:29 and arriving at 15:00, this newly found trip should not replace the already found one. 

You say that there can be "another trip that leaves later and arrives at the same time at the destination", but those later trips have already been examined and saved.

Unless you mean there can be a trip outside (after) the search time window. In that case the window must be enlarged: the end of the range raptor time window needs to be the latest time we'd be willing to arrive (as an optimization, minus some heuristically determined fastest possible travel time), not the latest we'd be willing to depart.

**Comment by t2gran** [comment]
Yes, I was meaning outside the time window. I will update the text above.
