### ISSUE TITLE
Weight function parameters (Entur)

### ISSUE THREAD

**Issue by gmellemstrand** [entur/r5#24]
Weight function for Entur. "Time" means time in seconds.

Walk: time * 4
Wait: 0.9 (experimental)
Wait at beginning: time * 0.4
Wait: time
Transit: time
Board transit: 300
Board/alight depending on stop classification. This is in addition to the fixed board cost: 0 / 60 / 150 / 3000 (preferred, recommended, allowed, no interchange)

Various walk costs: stairs, elevator etc.

**Comment by t2gran** [comment]
A cost function is now implemented:

```
Cost = walkReluctance * walkTime + waitReluctance * waitTime + boardCost * numTransits + transitTime.
```
There is no support for waitAtBeginning. I do not hink we need it - maybe later.
